### ISSUE TITLE
Blank screen on startup, keyring error on terminal

### ISSUE THREAD

**Issue by jvasile** [jellyflix-app/jellyflix#145]
### Please describe your bug

I did a fresh checkout from git, then `flutter run` and got the error below.  An application window popped up, but it was just a black rectangle with the typical flutter window decoration on top.

```
** (jellyflix:180788): WARNING **: 16:30:03.524: libsecret_error: Failed to unlock the keyring
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Libsecret error, Failed to unlock the keyring, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      SecureStorageService.read (package:jellyflix/services/secure_storage_service.dart:7:12)
<asynchronous suspension>
#3      DatabaseService.openBox (package:jellyflix/services/database_service.dart:32:19)
<asynchronous suspension>
#4      DatabaseService.initialize (package:jellyflix/services/database_service.dart:27:5)
<asynchronous suspension>
#5      main (package:jellyflix/main.dart:23:3)
<asynchronous suspension>
```

I'm on Linux, running Sway, which is a wayland compositor.  I don't generally use a keyring, but I appear to be running a keyring daemon:  Maybe it came in as a Network Manager dependency.

```
❯ ps ax | grep keyring
   9560 ?        Sl     0:00 /usr/bin/gnome-keyring-daemon --start --foreground --components=secrets
   9561 ?        SLsl   0:00 /usr/bin/gnome-keyring-daemon --foreground --components=pkcs11,secrets --control-directory=/run/user/1000/keyring
 181114 pts/0    S+     0:00 grep keyring
```

At any rate, I don't see any prompt to unlock a keyring or anything like that.  And the application didn't pause as if waiting for me to do a keyring unlock flow somewhere.

Thanks!

### Jellyflix Version

Other

### if other:

git checkout with hash of e370982

### Jellyfin Version

10.9.x

### Environment

```markdown
- OS: Linux
- OS Version: Debian Testing
- Playback Method: Didn't get this far
```

**Comment by jdk-21** [comment]
I could reproduce your issue. The problem seems to be already known: https://github.com/juliansteenbakker/flutter_secure_storage/issues/778
If this issue doesn't get fixed soon, we might have to implement a fallback method that works similar to macOS.

**Comment by jdk-21** [comment]
Hi @jvasile, I did add timeout since the future doesn't seem to complete. I'm currently working with a Pop OS 22.04 machine. This version isn't affected from the keyring error. 
You can try https://github.com/jellyflix-app/jellyflix/tree/fix/secure_storage_timeout
If this change works, let me know.

**Comment by shuplenkov** [comment]
When I open the fresh installed app on MacOs - I see black screen. Is it the same issue?

**Comment by jdk-21** [comment]
Hi, which version do you use? From the App Store, latest stable or prerelease?
This issue is about keyring problems with some Linux distros.

**Comment by shuplenkov** [comment]
1.4.3-preview0238

when I install 0.10.0 - I see login screen, but it doesn't work

**Comment by jdk-21** [comment]
@jvasile Cloud you try using a different keyring service like ksecretservice? AFAIK Sway doesnt has a preinstalled keyring service. This might be the problem here.

**Comment by juliansteenbakker** [comment]
The current implementation uses the develop branch of flutter_secure_storage. Does this fix the issue? Or is the issue still present? If so, i can look into debugging this.

**Comment by juliansteenbakker** [comment]
I'll try and setup an environment with ubuntu 24.10 to see if i can reproduce this. To be continued...
